name: Brand0n3
favicon: null
layout_spectrum: 0.868209317792207
typography_spectrum: 0.7843025559559464
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.19954356527887285
  lightness: 0.9072816756088287
  saturation: 0.17515904502943158
  rhythmicContrast: 0.30579991987906396
purpose: []
