name: Brand0n3
favicon: null
layout_spectrum: 0
typography_spectrum: 0.13712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-80775367-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
